docs: updated getting started for designers doc with font info
RocketCommunicationsInc/astro-www pull request #128
Opened 2023-02-15 19:48 UTC by micahjones13

This updates the getting started for designers page with new text regarding the fonts we use from google, (roboto, roboto mono). The text was pulled straight from the design confluence page linked in the ticket. 
Links that link out to external pages where verified to open in a new tab, as per the design confluence doc as well. 

JIRA: https://rocketcom.atlassian.net/browse/ASTRO-5609

2023-02-15 20:46 UTC, kiley-mitti approved these changes
Looks good!

2023-02-28 19:47 UTC, amalyah requested changes

2023-02-28 19:47 UTC, amalyah commented on src/pages/getting-started/designers.md
> +The Astro Figma files use fonts that are free to download from Google and linked below. Astro 6 Figma files use a combination of [Roboto](https://fonts.google.com/specimen/Roboto) and [Roboto Mono](h
Is it possible to put this after the links like we have on the Confluence page?

2023-03-02 20:35 UTC, amalyah approved these changes

2023-03-02 20:40 UTC, merged