feat(sitewide) change large breakpoint from 1728px to 1294px
RocketCommunicationsInc/astro-www pull request #264
Opened 2023-06-07 19:45 UTC by kiley-mitti

This changes our largest site breakpoint (the one that hides the sidebar) from 1728px down to 1294px.
I have added a couple of additional tweaks to wide tables to make sure they honor the new convention.
[Astro-6295](https://rocketcom.atlassian.net/browse/ASTRO-6295)

2023-06-12 14:08 UTC, FMorrison87 requested changes

2023-06-12 14:08 UTC, FMorrison87 commented on src/layouts/docs/style/page.css
> +	@media (1440px > width >= 1294px) {
I think the way these breakpoints are cascading needs to be reconfigured. I can't really read what's going on anymore. Could you take a stab at re-structuring these so they read in descending order?

2023-06-13 15:04 UTC, kiley-mitti commented on src/layouts/docs/style/page.css
> +	@media (1440px > width >= 1294px) {
I organized these breakpoints and changed around some of the variables. Can you check it out for me and see if this is a little more readable?

2023-06-13 18:39 UTC, FMorrison87 reviewed
Looks good!

2023-06-14 15:52 UTC, merged