(fix): Restore keyboard controls on search
RocketCommunicationsInc/astro-www pull request #43
Opened 2022-11-03 15:38 UTC by FMorrison87

Our new search did not have some of the keyboard controls that the search on the old website had. This PR now allows a keyboard user to:

- focus search input on cmd + k or ctrl + k
- ArrowUp and ArrowDown navigate results once the first result is focused.
- Enter selects result
- Escape clears results and search input

2022-11-07 13:47 UTC, jonathantneal requested changes
Pretty good. As a self-reminder; eventually, I should fix these in the upstream library.

2022-11-07 13:47 UTC, jonathantneal commented on src/components/site-search/site-search.client.ts
> +			if (event.key === 'k' && (event.metaKey || event.ctrlKey)) {
This is a bit tricky, but somewhere higher up we should to detect the appropriate modifier key.

```js
/** The modifier key of the platform ('Meta' for Apple devices, otherwise 'Control'). */
const modifierKey = /^(MacIntel|iPhone)$/.test(navigator.platform) ? 'metaKey' : 'ctrlKey'
```

And here, we can use this to detect if **k** was pressed with the appropriate modifier.

```js
if (event.key === 'k' && event[modifierKey]) {
```

Sadly, detecting the correct modifier key is still required, due to a missing web standard.

Refs:
- https://developer.mozilla.org/en-US/docs/Web/API/Navigator/platform#examples
- https://www.bennadel.com/blog/4090-capturing-keyboard-event-modifiers-across-operating-systems-in-javascript.htm
- https://stackoverflow.com/a/29035153

2022-11-07 13:47 UTC, jonathantneal commented on src/components/site-search/site-search.client.ts
> +									console.log(event.key)
Nit: Probably remove this.

Years ago, whenever I would leave these in code, my reviewer would write “WE’LL DO IT LIVE!” 😄

2022-11-07 13:47 UTC, jonathantneal commented on src/components/site-search/site-search.client.ts
> +									searchResults.replaceChildren('')
Nit: `replaceChildren` can receive 0 arguments.

2022-11-07 17:44 UTC, FMorrison87 commented on src/components/site-search/site-search.client.ts
> +					const resultChildren = searchResults.querySelectorAll('.listitem a')
Thank you sir!

2022-11-07 17:45 UTC, FMorrison87 commented on src/components/site-search/site-search.client.ts
> +						onkeydown = (event) => {
Yes, inside the resultChildren loop. Is there a better way for me to combine these?

2022-11-07 17:48 UTC, FMorrison87 commented on src/components/site-search/site-search.client.ts
> +			if (event.key === 'k' && (event.metaKey || event.ctrlKey)) {
I like this, it is a cleaner implementation than I had.

2022-11-08 19:21 UTC, jonathantneal commented on src/components/site-search/site-search.client.ts
> +						onkeydown = (event) => {
This has been moved out of an event, so it is resolved. 👍

2022-11-08 19:22 UTC, jonathantneal commented on src/components/site-search/site-search.css
> +		outline: none;
Q. Why is the outline being removed here?

2022-11-08 19:24 UTC, jonathantneal commented on src/components/site-search/site-search.client.ts
> +						onkeydown = (event) => {
Request: Move the arrow keydown behavior from the window to the input itself, using the event listener API.

2022-11-09 13:24 UTC, FMorrison87 commented on src/components/site-search/site-search.client.ts
> +						// })
This is all set now.

2022-11-09 13:25 UTC, FMorrison87 commented on src/components/site-search/site-search.css
> +		outline: none;
Trying to follow the paradigm that I see for the focus style since this 'aria-selected' style is essentially the same.

2022-11-09 14:03 UTC, FMorrison87 commented on src/components/site-search/site-search.client.ts
> +						onkeydown = (event) => {
ok, I believe I have done this, but let me know if the change wasn't what you were expecting.

2022-11-09 17:38 UTC, jonathantneal commented on src/components/site-search/site-search.client.ts
> +						onkeydown = (event) => {
👋 Thank you for looking. This is not the change I was expecting.

### How this bit should work

I am expecting the event listener to use the [Event API](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget), namely the `addEventListener` method, and I am expecting the down arrow key to be handled when the search element is focused. The code for that might something _like_ this:

```js
/** Handles a `keydown` event. */
const onKeydown = (event) => {
  if (event.key === 'ArrowDown') {
    // do something when the "down arrow" is key is pressed down
  }
}

searchElement.addEventListener('keydown', onKeydown)
```

### How this bit currently works

I get excited by code, so I hope it will be helpful to explain how this code is currently working.

Currently, the `onkeydown` is setting a value on an implicit reference to `window.onkeydown`, which listens to the `keydown` event after it [bubbles](https://stackoverflow.com/a/27073168) up from some element, up to or including the [`<body>`](https://w3c.github.io/uievents/#event-type-keydown). The flow goes something like this:

1. A key is pressed down.
2. If no element is focused, then `keydown` event is dispatched on `document.body`. Otherwise,
3. If an element is focused, the event is dispatched from the focused element.
4. The event bubbles up through the DOM tree.
   ```
   <body> → <html> → document → window
   ```
   ```
   <focused-element> → <possibly-parent> → <body> → <html> → document → window
   ```

2022-11-10 19:52 UTC, FMorrison87 commented on src/components/site-search/site-search.client.ts
> +						onkeydown = (event) => {
Ok check now.

2022-11-14 18:23 UTC, jonathantneal requested changes
I’ve requested a few smaller changes that should fix a remaining accessibility issue and remove some extra lookup logic that should (hopefully) happen implicitly.

2022-11-14 18:23 UTC, jonathantneal commented on src/components/site-search/site-search.client.ts
> +							console.log(result)
Nit: Remove any debugging & `console.log` statements before the merge.

2022-11-14 18:23 UTC, jonathantneal commented on src/components/site-search/site-search.client.ts
> +					if (indexNumber <= 3) {
Can this limit of `3` be documented, if it is a [magic number](https://codehs.com/glossary/term/14)? Otherwise, should it be changed into a calculation based on the number of available results (e.g. `indexNumber < resultChildren.length`)?

2022-11-14 18:23 UTC, jonathantneal commented on src/components/site-search/site-search.client.ts
> +	let resultChildren: any[] | NodeListOf<Element>
I think this should have an initial value of `[]` so that alter checks like `resultChildren.length` work before the initial search results are created.

2022-11-14 18:23 UTC, jonathantneal commented on src/components/site-search/site-search.client.ts
> +							result.setAttribute('aria-selected', '')
I think this will need to be changed to `result.setAttribute('aria-selected', 'true')`.

The `aria-selected` attribute takes a string value of `"true"` or `"false"` to indicate whether it is selected. An empty value means it is un-selectable. This is an area where web standards are not very intuitive. [ref](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-selected#values)

I find it’s a lot easier to test accessibility changes using the [Accessibility Tree tools built into DevTools](https://www.youtube.com/watch?v=Th-nv-SCj4Q&t=410s).

2022-11-15 15:28 UTC, jonathantneal approved these changes
This is good to merge. The suggestions are purely suggestions.

2022-11-15 15:28 UTC, jonathantneal commented on src/components/site-search/site-search.client.ts
> +		const onKeydown = (event: { key: string; preventDefault: () => void }) => {
If you don’t prefer this, or if it doesn’t work perfectly the first time, totally ignore it, and seriously, we should only blame TypeScript.

```suggestion
		const onKeydown = (event: KeyboardEvent) => {
```

2022-11-15 15:28 UTC, jonathantneal commented on src/components/site-search/site-search.client.ts
> +						}
Don’t use this, unless you genuinely prefer it.

```suggestion
						result.setAttribute('aria-selected', index === indexNumber)
```

2022-11-15 15:28 UTC, jonathantneal commented on src/components/site-search/site-search.client.ts
> +						}
Don’t use this, unless you genuinely prefer it.

```suggestion
						result.setAttribute('aria-selected', index === indexNumber)
```

2022-11-15 15:28 UTC, jonathantneal commented on src/components/site-search/site-search.client.ts
> +					// clears the search control and removes search results
Boom! 💯

2022-11-16 18:46 UTC, merged