Km events automation test
RocketCommunicationsInc/astro-www pull request #46
Opened 2022-11-08 20:49 UTC by kiley-mitti

This is just a test of using google calendar api to bring in events

2022-12-09 17:41 UTC, jonathantneal requested changes
Thanks for this. This looks great! I’ve requested some changes, but they’re mostly code organization & de-dupe stuff. :)

2022-12-09 17:41 UTC, jonathantneal commented on src/components/home/community/newevents.js
> +import { h } from 'project:utils/html.ts'
**Requests**:
- May we rename this file to something that communicates what it does? Maybe something like `home-community-events.update.js`?
- May we import shared methods from the shared source file?
-

2022-12-09 19:04 UTC, kiley-mitti commented on src/components/home/community/newevents.js
> +import { h } from 'project:utils/html.ts'
ok! I think I made the appropriate changes. :) I'll rerequest review

2022-12-12 15:20 UTC, kiley-mitti commented
@jonathantneal Sure thing! I've removed it. It's less relevant since the server side render makes sure that we are mostly up to date. We will want to make sure that it runs a nightly rebuild so that the site can grab fresh info.

2022-12-13 20:29 UTC, merged