create new tooltip page
RocketCommunicationsInc/astro-www pull request #77
Opened 2023-01-09 15:54 UTC by kiley-mitti

Created a new tooltip page for the tooltip component. Added under components in the menu. Added compliance rules in the compliance data.
[ASTRO-4978](https://rocketcom.atlassian.net/browse/ASTRO-4978)

We need to hold off on merging this until tooltip goes live because it links to a storybook entry that doesn't exist yet. Alternately we can hide storybook on the site for now and add a different ticket to put it back once tooltip is live.

2023-01-09 16:11 UTC, markacianfrani commented
ya hold off on merging this plz. itll automatically get published (might not be the end of the world). well want to merge this in when we release tooltip in figma/web.

2023-01-10 15:54 UTC, FMorrison87 requested changes
I left comments on the Confluence doc where the text is housed for design to review, but there are inaccuracies in the text that do not reflect the way the built component functions. [Tooltip Docs](https://rocketcom.atlassian.net/wiki/spaces/AS11/pages/2777120853/Tooltip+Designs)

2023-01-12 15:08 UTC, kiley-mitti commented
@FMorrison87 I think all the confluence comments have been resolved and I've updated the wording here to reflect that. Give it one more peek if you would. :)

2023-01-12 18:24 UTC, FMorrison87 approved these changes

2023-01-12 18:30 UTC, jonathantneal approved these changes

2023-01-12 18:30 UTC, merged